export interface Database {
  public: {
    Tables: {
      doctors: {
        Row: {
          id: string;
          user_id: string;
          full_name: string;
          email: string;
          phone: string | null;
          specialization: string;
          profile_image_url: string | null;
          facebook_url: string | null;
          instagram_url: string | null;
          linkedin_url: string | null;
          whatsapp_number: string | null;
          website_url: string | null;
          license_number: string | null;
          certificates: string[] | null;
          is_verified: boolean;
          is_onboarded: boolean;
          qualification: string | null;
          experience_years: number;
          registration_number: string | null;
          bio: string | null;
          languages_spoken: string[];
          services_offered: string[];
          cover_image_url: string | null;
          custom_specialization: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          full_name: string;
          email: string;
          phone?: string | null;
          specialization: string;
          profile_image_url?: string | null;
          facebook_url?: string | null;
          instagram_url?: string | null;
          linkedin_url?: string | null;
          whatsapp_number?: string | null;
          website_url?: string | null;
          license_number?: string | null;
          certificates?: string[] | null;
          is_verified?: boolean;
          is_onboarded?: boolean;
          qualification?: string | null;
          experience_years?: number;
          registration_number?: string | null;
          bio?: string | null;
          languages_spoken?: string[];
          services_offered?: string[];
          cover_image_url?: string | null;
          custom_specialization?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          full_name?: string;
          email?: string;
          phone?: string | null;
          specialization?: string;
          profile_image_url?: string | null;
          facebook_url?: string | null;
          instagram_url?: string | null;
          linkedin_url?: string | null;
          whatsapp_number?: string | null;
          website_url?: string | null;
          license_number?: string | null;
          certificates?: string[] | null;
          is_verified?: boolean;
          is_onboarded?: boolean;
          qualification?: string | null;
          experience_years?: number;
          registration_number?: string | null;
          bio?: string | null;
          languages_spoken?: string[];
          services_offered?: string[];
          cover_image_url?: string | null;
          custom_specialization?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      clinics: {
        Row: {
          id: string;
          doctor_id: string;
          name: string;
          slug: string | null;
          address: string;
          city: string;
          state: string | null;
          country: string;
          postal_code: string | null;
          phone: string | null;
          email: string | null;
          website: string | null;
          logo_url: string | null;
          gallery_images: string[] | null;
          consultation_fee: number;
          slot_duration_minutes: number;
          booking_mode: "auto" | "manual";
          is_active: boolean;
          about: string | null;
          cover_image_url: string | null;
          latitude: number | null;
          longitude: number | null;
          consultation_type: "in_person" | "online" | "both";
          buffer_time_minutes: number;
          facilities: string[];
          languages_spoken: string[];
          is_featured: boolean;
          account_status: "active" | "suspended" | "deactivated";
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          doctor_id: string;
          name: string;
          slug?: string | null;
          address: string;
          city: string;
          state?: string | null;
          country?: string;
          postal_code?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          logo_url?: string | null;
          gallery_images?: string[] | null;
          consultation_fee?: number;
          slot_duration_minutes?: number;
          booking_mode?: "auto" | "manual";
          is_active?: boolean;
          about?: string | null;
          cover_image_url?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          consultation_type?: "in_person" | "online" | "both";
          buffer_time_minutes?: number;
          facilities?: string[];
          languages_spoken?: string[];
          is_featured?: boolean;
          account_status?: "active" | "suspended" | "deactivated";
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          doctor_id?: string;
          name?: string;
          slug?: string | null;
          address?: string;
          city?: string;
          state?: string | null;
          country?: string;
          postal_code?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          logo_url?: string | null;
          gallery_images?: string[] | null;
          consultation_fee?: number;
          slot_duration_minutes?: number;
          booking_mode?: "auto" | "manual";
          is_active?: boolean;
          about?: string | null;
          cover_image_url?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          consultation_type?: "in_person" | "online" | "both";
          buffer_time_minutes?: number;
          facilities?: string[];
          languages_spoken?: string[];
          is_featured?: boolean;
          account_status?: "active" | "suspended" | "deactivated";
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      patients: {
        Row: {
          id: string;
          user_id: string | null;
          full_name: string;
          email: string | null;
          phone: string | null;
          date_of_birth: string | null;
          gender: "male" | "female" | "other" | null;
          address: string | null;
          is_guest: boolean;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          medical_history: string | null;
          created_at: string;
          deleted_at: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          full_name: string;
          email?: string | null;
          phone?: string | null;
          date_of_birth?: string | null;
          gender?: "male" | "female" | "other" | null;
          address?: string | null;
          is_guest?: boolean;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          medical_history?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          full_name?: string;
          email?: string | null;
          phone?: string | null;
          date_of_birth?: string | null;
          gender?: "male" | "female" | "other" | null;
          address?: string | null;
          is_guest?: boolean;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          medical_history?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      availability_overrides: {
        Row: {
          id: string;
          clinic_id: string;
          date: string;
          start_time: string | null;
          end_time: string | null;
          is_available: boolean;
          reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          date: string;
          start_time?: string | null;
          end_time?: string | null;
          is_available?: boolean;
          reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          date?: string;
          start_time?: string | null;
          end_time?: string | null;
          is_available?: boolean;
          reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_blocks: {
        Row: {
          id: string;
          conversation_id: string;
          blocker_type: "doctor" | "patient";
          blocker_id: string;
          blocked_user_id: string;
          reason: string;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          blocker_type: "doctor" | "patient";
          blocker_id: string;
          blocked_user_id: string;
          reason?: string;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          blocker_type?: "doctor" | "patient";
          blocker_id?: string;
          blocked_user_id?: string;
          reason?: string;
          description?: string | null;
          created_at?: string;
        };
      };
      availability: {
        Row: {
          id: string;
          clinic_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          day_of_week?: number;
          start_time?: string;
          end_time?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      doctor_breaks: {
        Row: {
          id: string;
          clinic_id: string;
          break_type: "lunch" | "prayer" | "custom";
          title: string | null;
          day_of_week: number;
          start_time: string;
          end_time: string;
          is_recurring: boolean;
          specific_date: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          break_type: "lunch" | "prayer" | "custom";
          title?: string | null;
          day_of_week: number;
          start_time: string;
          end_time: string;
          is_recurring?: boolean;
          specific_date?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          break_type?: "lunch" | "prayer" | "custom";
          title?: string | null;
          day_of_week?: number;
          start_time?: string;
          end_time?: string;
          is_recurring?: boolean;
          specific_date?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      doctor_holidays: {
        Row: {
          id: string;
          clinic_id: string;
          title: string;
          start_date: string;
          end_date: string;
          is_all_day: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          title: string;
          start_date: string;
          end_date: string;
          is_all_day?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          title?: string;
          start_date?: string;
          end_date?: string;
          is_all_day?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      appointments: {
        Row: {
          id: string;
          clinic_id: string;
          doctor_id: string;
          patient_id: string;
          appointment_date: string;
          start_time: string;
          end_time: string;
          status: "pending" | "confirmed" | "completed" | "cancelled" | "no_show";
          reason_for_visit: string | null;
          notes: string | null;
          cancellation_reason: string | null;
          cancelled_by: "doctor" | "patient" | "system" | null;
          cancelled_at: string | null;
          no_show_marked_at: string | null;
          no_show_marked_by: string | null;
          completed_at: string | null;
          rescheduled_from: Record<string, unknown> | null;
          rescheduled_at: string | null;
          reference_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          doctor_id: string;
          patient_id: string;
          appointment_date: string;
          start_time: string;
          end_time: string;
          status?: "pending" | "confirmed" | "completed" | "cancelled" | "no_show";
          reason_for_visit?: string | null;
          notes?: string | null;
          cancellation_reason?: string | null;
          cancelled_by?: "doctor" | "patient" | "system" | null;
          cancelled_at?: string | null;
          no_show_marked_at?: string | null;
          no_show_marked_by?: string | null;
          completed_at?: string | null;
          rescheduled_from?: Record<string, unknown> | null;
          rescheduled_at?: string | null;
          reference_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          doctor_id?: string;
          patient_id?: string;
          appointment_date?: string;
          start_time?: string;
          end_time?: string;
          status?: "pending" | "confirmed" | "completed" | "cancelled" | "no_show";
          reason_for_visit?: string | null;
          notes?: string | null;
          cancellation_reason?: string | null;
          cancelled_by?: "doctor" | "patient" | "system" | null;
          cancelled_at?: string | null;
          no_show_marked_at?: string | null;
          no_show_marked_by?: string | null;
          completed_at?: string | null;
          rescheduled_from?: Record<string, unknown> | null;
          rescheduled_at?: string | null;
          reference_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          doctor_id: string;
          status: "active" | "resolved";
          last_message_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          patient_id: string;
          doctor_id: string;
          status?: "active" | "resolved";
          last_message_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          patient_id?: string;
          doctor_id?: string;
          status?: "active" | "resolved";
          last_message_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          sender_type: "doctor" | "patient";
          content: string;
          is_read: boolean;
          read_at: string | null;
          delivery_status: "pending" | "delivered" | "read" | "failed" | null;
          attachments: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender_id: string;
          sender_type: "doctor" | "patient";
          content: string;
          is_read?: boolean;
          read_at?: string | null;
          delivery_status?: "pending" | "delivered" | "read" | "failed" | null;
          attachments?: string[] | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          sender_id?: string;
          sender_type?: "doctor" | "patient";
          content?: string;
          is_read?: boolean;
          read_at?: string | null;
          delivery_status?: "pending" | "delivered" | "read" | "failed" | null;
          attachments?: string[] | null;
          created_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          doctor_id: string;
          patient_id: string;
          appointment_id: string | null;
          rating: number;
          comment: string | null;
          is_verified: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          doctor_id: string;
          patient_id: string;
          appointment_id?: string | null;
          rating: number;
          comment?: string | null;
          is_verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          doctor_id?: string;
          patient_id?: string;
          appointment_id?: string | null;
          rating?: number;
          comment?: string | null;
          is_verified?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      patient_favorites: {
        Row: {
          id: string;
          patient_id: string;
          doctor_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          patient_id: string;
          doctor_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          patient_id?: string;
          doctor_id?: string;
          created_at?: string;
        };
      };
      broadcast_messages: {
        Row: {
          id: string;
          doctor_id: string;
          clinic_id: string;
          message: string;
          sent_at: string;
          recipient_count: number;
        };
        Insert: {
          id?: string;
          doctor_id: string;
          clinic_id: string;
          message: string;
          sent_at?: string;
          recipient_count?: number;
        };
        Update: {
          id?: string;
          doctor_id?: string;
          clinic_id?: string;
          message?: string;
          sent_at?: string;
          recipient_count?: number;
        };
      };
      otp_verifications: {
        Row: {
          id: string;
          phone: string;
          otp_code: string;
          purpose: "booking" | "cancel" | "reschedule" | "lookup";
          reference_id: string | null;
          expires_at: string;
          verified: boolean;
          verified_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          phone: string;
          otp_code: string;
          purpose: "booking" | "cancel" | "reschedule" | "lookup";
          reference_id?: string | null;
          expires_at: string;
          verified?: boolean;
          verified_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          phone?: string;
          otp_code?: string;
          purpose?: "booking" | "cancel" | "reschedule" | "lookup";
          reference_id?: string | null;
          expires_at?: string;
          verified?: boolean;
          verified_at?: string | null;
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          user_type: "doctor" | "patient";
          type: "appointment_confirmed" | "appointment_pending" | "appointment_rejected" | "appointment_cancelled" | "appointment_completed" | "appointment_no_show" | "appointment_rescheduled" | "appointment_reminder_24h" | "appointment_reminder_2h" | "new_message" | "chat_reply" | "doctor_verified" | "review_submitted" | "subscription_updated" | "featured_status";
          title: string;
          body: string;
          data: Record<string, unknown>;
          is_read: boolean;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          user_type: "doctor" | "patient";
          type: "appointment_confirmed" | "appointment_pending" | "appointment_rejected" | "appointment_cancelled" | "appointment_completed" | "appointment_no_show" | "appointment_rescheduled" | "appointment_reminder_24h" | "appointment_reminder_2h" | "new_message" | "chat_reply" | "doctor_verified" | "review_submitted" | "subscription_updated" | "featured_status";
          title: string;
          body: string;
          data?: Record<string, unknown>;
          is_read?: boolean;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          user_type?: "doctor" | "patient";
          type?: "appointment_confirmed" | "appointment_pending" | "appointment_rejected" | "appointment_cancelled" | "appointment_completed" | "appointment_reminder_24h" | "appointment_reminder_2h" | "new_message" | "chat_reply";
          title?: string;
          body?: string;
          data?: Record<string, unknown>;
          is_read?: boolean;
          read_at?: string | null;
          created_at?: string;
        };
      };
      subscription_plans: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          price_monthly: number;
          price_yearly: number;
          features: string[];
          limits: Record<string, number>;
          is_active: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string | null;
          price_monthly: number;
          price_yearly: number;
          features?: string[];
          limits?: Record<string, number>;
          is_active?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string | null;
          price_monthly?: number;
          price_yearly?: number;
          features?: string[];
          limits?: Record<string, number>;
          is_active?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      doctor_subscriptions: {
        Row: {
          id: string;
          doctor_id: string;
          plan_id: string | null;
          status: "trial" | "active" | "past_due" | "grace" | "cancelled" | "expired";
          billing_cycle: "monthly" | "yearly" | null;
          external_subscription_id: string | null;
          external_customer_id: string | null;
          trial_started_at: string | null;
          trial_ends_at: string | null;
          current_period_start: string | null;
          current_period_end: string | null;
          cancelled_at: string | null;
          grace_period_ends_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          doctor_id: string;
          plan_id?: string | null;
          status?: "trial" | "active" | "past_due" | "grace" | "cancelled" | "expired";
          billing_cycle?: "monthly" | "yearly" | null;
          external_subscription_id?: string | null;
          external_customer_id?: string | null;
          trial_started_at?: string | null;
          trial_ends_at?: string | null;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancelled_at?: string | null;
          grace_period_ends_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          doctor_id?: string;
          plan_id?: string | null;
          status?: "trial" | "active" | "past_due" | "grace" | "cancelled" | "expired";
          billing_cycle?: "monthly" | "yearly" | null;
          external_subscription_id?: string | null;
          external_customer_id?: string | null;
          trial_started_at?: string | null;
          trial_ends_at?: string | null;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancelled_at?: string | null;
          grace_period_ends_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      featured_listings: {
        Row: {
          id: string;
          doctor_id: string;
          status: "active" | "inactive" | "expired";
          started_at: string | null;
          expires_at: string | null;
          subscription_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          doctor_id: string;
          status?: "active" | "inactive" | "expired";
          started_at?: string | null;
          expires_at?: string | null;
          subscription_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          doctor_id?: string;
          status?: "active" | "inactive" | "expired";
          started_at?: string | null;
          expires_at?: string | null;
          subscription_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      legal_consents: {
        Row: {
          id: string;
          user_type: "doctor" | "patient" | "guest";
          user_id: string | null;
          guest_identifier: string | null;
          consent_type: "terms" | "privacy" | "cookies" | "booking_terms";
          version: string;
          source_action: string;
          ip_address: string | null;
          user_agent: string | null;
          accepted_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_type: "doctor" | "patient" | "guest";
          user_id?: string | null;
          guest_identifier?: string | null;
          consent_type: "terms" | "privacy" | "cookies" | "booking_terms";
          version?: string;
          source_action: string;
          ip_address?: string | null;
          user_agent?: string | null;
          accepted_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_type?: "doctor" | "patient" | "guest";
          user_id?: string | null;
          guest_identifier?: string | null;
          consent_type?: "terms" | "privacy" | "cookies" | "booking_terms";
          version?: string;
          source_action?: string;
          ip_address?: string | null;
          user_agent?: string | null;
          accepted_at?: string;
          created_at?: string;
        };
      };
      billing_events: {
        Row: {
          id: string;
          doctor_subscription_id: string | null;
          event_type: string;
          external_event_id: string | null;
          provider: string;
          payload: Record<string, unknown>;
          processed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          doctor_subscription_id?: string | null;
          event_type: string;
          external_event_id?: string | null;
          provider?: string;
          payload?: Record<string, unknown>;
          processed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          doctor_subscription_id?: string | null;
          event_type?: string;
          external_event_id?: string | null;
          provider?: string;
          payload?: Record<string, unknown>;
          processed_at?: string | null;
          created_at?: string;
        };
      };
      admin_roles: {
        Row: {
          id: string;
          user_id: string;
          role: "super_admin" | "admin" | "moderator" | "viewer";
          permissions: Record<string, boolean>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          role?: "super_admin" | "admin" | "moderator" | "viewer";
          permissions?: Record<string, boolean>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          role?: "super_admin" | "admin" | "moderator" | "viewer";
          permissions?: Record<string, boolean>;
          created_at?: string;
          updated_at?: string;
        };
      };
      verification_documents: {
        Row: {
          id: string;
          doctor_id: string;
          document_type: "license" | "certificate" | "clinic_proof" | "id_card" | "profile_photo" | "other";
          file_path: string;
          file_name: string;
          file_size: number;
          mime_type: string;
          status: "pending" | "approved" | "rejected" | "resubmit";
          rejection_reason: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          uploaded_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          doctor_id: string;
          document_type: "license" | "certificate" | "clinic_proof" | "id_card" | "profile_photo" | "other";
          file_path: string;
          file_name: string;
          file_size: number;
          mime_type: string;
          status?: "pending" | "approved" | "rejected" | "resubmit";
          rejection_reason?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          uploaded_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          doctor_id?: string;
          document_type?: "license" | "certificate" | "clinic_proof" | "id_card" | "profile_photo" | "other";
          file_path?: string;
          file_name?: string;
          file_size?: number;
          mime_type?: string;
          status?: "pending" | "approved" | "rejected" | "resubmit";
          rejection_reason?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          uploaded_at?: string;
          created_at?: string;
        };
      };
      verification_requests: {
        Row: {
          id: string;
          doctor_id: string;
          status: "pending" | "under_review" | "approved" | "rejected" | "resubmit" | "suspended";
          submitted_at: string;
          reviewed_by: string | null;
          reviewed_at: string | null;
          internal_notes: string | null;
          rejection_reason: string | null;
          approved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          doctor_id: string;
          status?: "pending" | "under_review" | "approved" | "rejected" | "resubmit" | "suspended";
          submitted_at?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          internal_notes?: string | null;
          rejection_reason?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          doctor_id?: string;
          status?: "pending" | "under_review" | "approved" | "rejected" | "resubmit" | "suspended";
          submitted_at?: string;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          internal_notes?: string | null;
          rejection_reason?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          admin_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          before_data: Record<string, unknown> | null;
          after_data: Record<string, unknown> | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          admin_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          before_data?: Record<string, unknown> | null;
          after_data?: Record<string, unknown> | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          admin_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          before_data?: Record<string, unknown> | null;
          after_data?: Record<string, unknown> | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
      support_tickets: {
        Row: {
          id: string;
          requester_type: "doctor" | "patient" | "guest";
          requester_id: string | null;
          requester_email: string;
          requester_name: string;
          subject: string;
          message: string;
          priority: "low" | "normal" | "high" | "urgent";
          status: "open" | "in_progress" | "waiting" | "resolved" | "closed";
          assigned_to: string | null;
          category: string | null;
          created_at: string;
          updated_at: string;
          resolved_at: string | null;
        };
        Insert: {
          id?: string;
          requester_type: "doctor" | "patient" | "guest";
          requester_id?: string | null;
          requester_email: string;
          requester_name: string;
          subject: string;
          message: string;
          priority?: "low" | "normal" | "high" | "urgent";
          status?: "open" | "in_progress" | "waiting" | "resolved" | "closed";
          assigned_to?: string | null;
          category?: string | null;
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
        };
        Update: {
          id?: string;
          requester_type?: "doctor" | "patient" | "guest";
          requester_id?: string | null;
          requester_email?: string;
          requester_name?: string;
          subject?: string;
          message?: string;
          priority?: "low" | "normal" | "high" | "urgent";
          status?: "open" | "in_progress" | "waiting" | "resolved" | "closed";
          assigned_to?: string | null;
          category?: string | null;
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
        };
      };
      support_ticket_messages: {
        Row: {
          id: string;
          ticket_id: string;
          sender_type: "admin" | "requester";
          sender_id: string | null;
          message: string;
          attachments: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          sender_type: "admin" | "requester";
          sender_id?: string | null;
          message: string;
          attachments?: string[];
          created_at?: string;
        };
        Update: {
          id?: string;
          ticket_id?: string;
          sender_type?: "admin" | "requester";
          sender_id?: string | null;
          message?: string;
          attachments?: string[];
          created_at?: string;
        };
      };
      reports: {
        Row: {
          id: string;
          reporter_type: "doctor" | "patient" | "guest" | "system";
          reporter_id: string | null;
          reporter_email: string | null;
          reported_entity_type: "doctor" | "clinic" | "patient" | "review" | "appointment";
          reported_entity_id: string;
          reason: string;
          description: string | null;
          status: "pending" | "investigating" | "resolved" | "dismissed";
          assigned_to: string | null;
          resolution_notes: string | null;
          created_at: string;
          updated_at: string;
          resolved_at: string | null;
        };
        Insert: {
          id?: string;
          reporter_type: "doctor" | "patient" | "guest" | "system";
          reporter_id?: string | null;
          reporter_email?: string | null;
          reported_entity_type: "doctor" | "clinic" | "patient" | "review" | "appointment";
          reported_entity_id: string;
          reason: string;
          description?: string | null;
          status?: "pending" | "investigating" | "resolved" | "dismissed";
          assigned_to?: string | null;
          resolution_notes?: string | null;
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
        };
        Update: {
          id?: string;
          reporter_type?: "doctor" | "patient" | "guest" | "system";
          reporter_id?: string | null;
          reporter_email?: string | null;
          reported_entity_type?: "doctor" | "clinic" | "patient" | "review" | "appointment";
          reported_entity_id?: string;
          reason?: string;
          description?: string | null;
          status?: "pending" | "investigating" | "resolved" | "dismissed";
          assigned_to?: string | null;
          resolution_notes?: string | null;
          created_at?: string;
          updated_at?: string;
          resolved_at?: string | null;
        };
      };
      platform_settings: {
        Row: {
          id: string;
          key: string;
          value: Record<string, unknown>;
          description: string | null;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          value: Record<string, unknown>;
          description?: string | null;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          value?: Record<string, unknown>;
          description?: string | null;
          updated_by?: string | null;
          updated_at?: string;
        };
      };
      events: {
        Row: {
          id: string;
          event_type: string;
          actor_type: string | null;
          actor_id: string | null;
          target_type: string | null;
          target_id: string | null;
          clinic_id: string | null;
          doctor_id: string | null;
          patient_id: string | null;
          appointment_id: string | null;
          metadata: Record<string, unknown>;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_type: string;
          actor_type?: string | null;
          actor_id?: string | null;
          target_type?: string | null;
          target_id?: string | null;
          clinic_id?: string | null;
          doctor_id?: string | null;
          patient_id?: string | null;
          appointment_id?: string | null;
          metadata?: Record<string, unknown>;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_type?: string;
          actor_type?: string | null;
          actor_id?: string | null;
          target_type?: string | null;
          target_id?: string | null;
          clinic_id?: string | null;
          doctor_id?: string | null;
          patient_id?: string | null;
          appointment_id?: string | null;
          metadata?: Record<string, unknown>;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
      push_tokens: {
        Row: {
          id: string;
          user_type: "doctor" | "patient";
          user_id: string;
          token: string;
          endpoint: string | null;
          platform: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_type: "doctor" | "patient";
          user_id: string;
          token: string;
          endpoint?: string | null;
          platform?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_type?: "doctor" | "patient";
          user_id?: string;
          token?: string;
          endpoint?: string | null;
          platform?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      notification_queue: {
        Row: {
          id: string;
          user_type: string;
          user_id: string;
          notification_type: string;
          title: string;
          body: string | null;
          data: Record<string, unknown>;
          channels: string[];
          status: string;
          retry_count: number;
          max_retries: number;
          next_retry_at: string | null;
          last_error: string | null;
          sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_type: string;
          user_id: string;
          notification_type: string;
          title: string;
          body?: string | null;
          data?: Record<string, unknown>;
          channels?: string[];
          status?: string;
          retry_count?: number;
          max_retries?: number;
          next_retry_at?: string | null;
          last_error?: string | null;
          sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_type?: string;
          user_id?: string;
          notification_type?: string;
          title?: string;
          body?: string | null;
          data?: Record<string, unknown>;
          channels?: string[];
          status?: string;
          retry_count?: number;
          max_retries?: number;
          next_retry_at?: string | null;
          last_error?: string | null;
          sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      feature_flags: {
        Row: {
          id: string;
          key: string;
          label: string;
          description: string | null;
          is_enabled: boolean;
          category: string;
          is_system: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          label: string;
          description?: string | null;
          is_enabled?: boolean;
          category?: string;
          is_system?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          label?: string;
          description?: string | null;
          is_enabled?: boolean;
          category?: string;
          is_system?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      help_categories: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string | null;
          icon: string;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description?: string | null;
          icon?: string;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string | null;
          icon?: string;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      help_articles: {
        Row: {
          id: string;
          category_id: string;
          slug: string;
          title: string;
          content: string;
          summary: string | null;
          tags: string[];
          display_order: number;
          is_published: boolean;
          view_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          category_id: string;
          slug: string;
          title: string;
          content: string;
          summary?: string | null;
          tags?: string[];
          display_order?: number;
          is_published?: boolean;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          category_id?: string;
          slug?: string;
          title?: string;
          content?: string;
          summary?: string | null;
          tags?: string[];
          display_order?: number;
          is_published?: boolean;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      help_feedback: {
        Row: {
          id: string;
          article_id: string;
          is_helpful: boolean;
          comment: string | null;
          user_identifier: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          article_id: string;
          is_helpful: boolean;
          comment?: string | null;
          user_identifier?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          article_id?: string;
          is_helpful?: boolean;
          comment?: string | null;
          user_identifier?: string | null;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}

export type Doctor = Database["public"]["Tables"]["doctors"]["Row"];
export type Clinic = Database["public"]["Tables"]["clinics"]["Row"];
export type Patient = Database["public"]["Tables"]["patients"]["Row"];
export type Availability = Database["public"]["Tables"]["availability"]["Row"];
export type DoctorBreak = Database["public"]["Tables"]["doctor_breaks"]["Row"];
export type DoctorHoliday = Database["public"]["Tables"]["doctor_holidays"]["Row"];
export type Appointment = Database["public"]["Tables"]["appointments"]["Row"];
export type Conversation = Database["public"]["Tables"]["conversations"]["Row"];
export type Message = Database["public"]["Tables"]["messages"]["Row"];
export type Review = Database["public"]["Tables"]["reviews"]["Row"];
export type PatientFavorite = Database["public"]["Tables"]["patient_favorites"]["Row"];
export type BroadcastMessage = Database["public"]["Tables"]["broadcast_messages"]["Row"];
export type OtpVerification = Database["public"]["Tables"]["otp_verifications"]["Row"];
export type Notification = Database["public"]["Tables"]["notifications"]["Row"];
export type SubscriptionPlan = Database["public"]["Tables"]["subscription_plans"]["Row"];
export type DoctorSubscription = Database["public"]["Tables"]["doctor_subscriptions"]["Row"];
export type FeaturedListing = Database["public"]["Tables"]["featured_listings"]["Row"];
export type LegalConsent = Database["public"]["Tables"]["legal_consents"]["Row"];
export type BillingEvent = Database["public"]["Tables"]["billing_events"]["Row"];
export type AdminRole = Database["public"]["Tables"]["admin_roles"]["Row"];
export type VerificationDocument = Database["public"]["Tables"]["verification_documents"]["Row"];
export type VerificationRequest = Database["public"]["Tables"]["verification_requests"]["Row"];
export type AuditLog = Database["public"]["Tables"]["audit_logs"]["Row"];
export type SupportTicket = Database["public"]["Tables"]["support_tickets"]["Row"];
export type SupportTicketMessage = Database["public"]["Tables"]["support_ticket_messages"]["Row"];
export type Report = Database["public"]["Tables"]["reports"]["Row"];
export type PlatformSetting = Database["public"]["Tables"]["platform_settings"]["Row"];
export type Event = Database["public"]["Tables"]["events"]["Row"];
export type NotificationQueueItem = Database["public"]["Tables"]["notification_queue"]["Row"];
export type PushToken = Database["public"]["Tables"]["push_tokens"]["Row"];
export type AvailabilityOverride = Database["public"]["Tables"]["availability_overrides"]["Row"];
export type UserBlock = Database["public"]["Tables"]["user_blocks"]["Row"];
